sudo: required
dist: trusty
before_script:
    - sudo apt-get install -y yasm nasm
    - ./autogen.sh
script: ./configure && make && make check
language: c
compiler:
    - clang
    - gcc
env:
    - AS=yasm
    - AS=nasm
